import { Passenger } from '../types';

// Datos extraídos del archivo proporcionado
export const defaultPassengersData = [
  { cedula: "5851039", name: "LUIS FRANCISCO GOMEZ CASADIEGO", gerencia: "AIT" },
  { cedula: "9717201", name: "DAIVYS LUIS DIAZ ROJAS", gerencia: "AIT" },
  { cedula: "10944635", name: "HAZEL JOSEFINA AGUILERA RODRIGUEZ", gerencia: "AIT" },
  { cedula: "10967425", name: "JOSE ANGEL TROMPIZ MUSHART", gerencia: "AIT" },
  { cedula: "11253723", name: "RAFAEL EMIRO CAMARGO GARCIA", gerencia: "AIT" },
  { cedula: "11479380", name: "RICHARD ALEXANDER GALIZ RIVERO", gerencia: "AIT" },
  { cedula: "11803579", name: "YANIRA ANTONIA PEREIRA SIRIT", gerencia: "AIT" },
  { cedula: "13002493", name: "RAMIRO SEGUNDO MONTERO DIAZ", gerencia: "AIT" },
  { cedula: "13180609", name: "NILECTO NOE LEON SALAS", gerencia: "AIT" },
  { cedula: "13878642", name: "LISBETH CELINA PIÑA MARIN", gerencia: "AIT" },
  { cedula: "14893331", name: "VIRGILIO MUÑOZ MARTINS", gerencia: "AIT" },
  { cedula: "15162142", name: "ALEXANDER JOSE REYES ARELLANES", gerencia: "AIT" },
  { cedula: "15553385", name: "NERVIS ENRIQUE CARDOZO ANCIANI", gerencia: "AIT" },
  { cedula: "16017790", name: "MERVIN RICARDO GONZALEZ GONZALEZ", gerencia: "AIT" },
  { cedula: "18119712", name: "VERONICA ISABEL QUEVEDO FERNANDEZ", gerencia: "AIT" },
  { cedula: "18202708", name: "EDWIN MARIANO BRACHO RIOS", gerencia: "AIT" },
  { cedula: "18409618", name: "ANDRES JOHAN DE LA ROSA PEREZ", gerencia: "AIT" },
  { cedula: "18494991", name: "WILLIAM MARIN MADRID", gerencia: "AIT" },
  { cedula: "19214501", name: "JOSE GUILLERMO VILLASMIL PRIMERA", gerencia: "AIT" },
  { cedula: "15938957", name: "ANNIAK CAROLINA RANGEL DE DIAZ", gerencia: "AIT" },
  { cedula: "17918958", name: "ALEJANDRO JOSE ANGULO FERREIDA", gerencia: "AIT" },
  { cedula: "13930420", name: "EDDY JOSE AÑEZ", gerencia: "ASUNTOS PUBLICOS" },
  { cedula: "14206794", name: "NAIBELYN AURORA PRIETO VILLALOBOS", gerencia: "ASUNTOS PUBLICOS" },
  { cedula: "16120461", name: "BIANCA GUADALUPE FUENMAYOR MENDOZA", gerencia: "ASUNTOS PUBLICOS" },
  { cedula: "19906567", name: "DIBETSI ANDREINA MUÑOZ RUBIO", gerencia: "ASUNTOS PUBLICOS" },
  { cedula: "22140339", name: "ANDREA NOEMI CHIRINO ESPINA", gerencia: "ASUNTOS PUBLICOS" },
  { cedula: "7864550", name: "JOSE GREGORIO MADRIZ PAREDES", gerencia: "CONTRATACION" },
  { cedula: "11283478", name: "MORAIMA CHIQUINQUIRA GONZALEZ AMAYA", gerencia: "CONTRATACION" },
  { cedula: "13495284", name: "MARWILL ALBERTO MORONTA RODRIGUEZ", gerencia: "CONTRATACION" },
  { cedula: "14084138", name: "YLIANA JOSEFINA SILVA LABARCA", gerencia: "CONTRATACION" },
  { cedula: "14448228", name: "YASMELY DEL CARMEN CELEDON DE ENGELMANN", gerencia: "CONTRATACION" },
  { cedula: "14863952", name: "FABIANA MENDOZA MARTINEZ", gerencia: "CONTRATACION" },
  { cedula: "16622010", name: "DAYANA CAROLINA CHAPARRO BERNAL", gerencia: "CONTRATACION" },
  { cedula: "16755526", name: "HASNEY COROMOTO MEDINA CARTAYA", gerencia: "CONTRATACION" },
  { cedula: "18342839", name: "MOISES ALEJANDRO ISEA QUINTERO", gerencia: "CONTRATACION" },
  { cedula: "22134565", name: "JESUS DANIEL MARQUEZ DIOMAIUTO", gerencia: "CONTRATACION" },
  { cedula: "23760427", name: "FRANCIS CAROLINA GIL SANCHEZ", gerencia: "CONTRATACION" },
  { cedula: "23876264", name: "MAINERY NAVA", gerencia: "CONTRATACION" },
  { cedula: "24381489", name: "NESTOR XAVIER FINOL GARCIA", gerencia: "CONTRATACION" },
  { cedula: "26092010", name: "CARLOS ENRIQUE CANCHICA GUERRA", gerencia: "CONTRATACION" },
  { cedula: "27360665", name: "JUAN DIEGO ARANGUREN BOHORQUEZ", gerencia: "CONTRATACION" },
  { cedula: "27367704", name: "EMILY LABARCA", gerencia: "CONTRATACION" },
  { cedula: "17567119", name: "JOIVAN ENRIQUE ECHEVERRIA OLIVAR", gerencia: "CONTRATACION" },
  { cedula: "7819558", name: "RAMSES DE JESUS DARWICH URDANETA", gerencia: "DSI" },
  { cedula: "7966763", name: "JORGE SEGUNDO TEJEDOR RODRIGUEZ", gerencia: "DSI" },
  { cedula: "8502909", name: "ROBERT EZEQUIEL MENDOZA MORA", gerencia: "DSI" },
  { cedula: "8708255", name: "MARIN ENRIQUE MOLINA MARQUEZ", gerencia: "DSI" },
  { cedula: "9714324", name: "FILODEO CIANFAGLIONE GUILLEN", gerencia: "DSI" },
  { cedula: "9728254", name: "ALEXANDER DANIEL RAMIREZ", gerencia: "DSI" },
  { cedula: "9729881", name: "FRANZ REYNALDO BARRIOS", gerencia: "DSI" },
  { cedula: "9744241", name: "ARELIS JOSEFINA MONTERO DE NUÑEZ", gerencia: "DSI" },
  { cedula: "9754526", name: "DANIEL SEGUNDO CHOURIO CHOURIO", gerencia: "DSI" },
  { cedula: "9788086", name: "JOSE LUIS MUÑOZ COLINA", gerencia: "DSI" },
  { cedula: "9789361", name: "MANUEL ANTONIO PEñA VALERA", gerencia: "DSI" },
  { cedula: "10414879", name: "DOMIEL KENT ARIAS GARCIA", gerencia: "DSI" },
  { cedula: "10416001", name: "GRABIEL JOSE MONTIEL BERRIOS", gerencia: "DSI" },
  { cedula: "10450129", name: "JOSE LUIS PADILLA LARREAL", gerencia: "DSI" },
  { cedula: "10725976", name: "JOSE LUIS MUJICA ALVAREZ", gerencia: "DSI" },
  { cedula: "10887357", name: "EDMUNDO JOSE RUIZ OJEDA", gerencia: "DSI" },
  { cedula: "11066877", name: "EUGENIO DE JESUS PEREZ RAMIREZ", gerencia: "DSI" },
  { cedula: "11283763", name: "FERNANDO ENRIQUE PAZ DIAZ", gerencia: "DSI" },
  { cedula: "11298239", name: "ENDER JOSE REVILLA MORALES", gerencia: "DSI" },
  { cedula: "11389115", name: "AIME JOSE GALLARDO URDANETA", gerencia: "DSI" },
  { cedula: "11394257", name: "JUAN CARLOS OBERTO GIL", gerencia: "DSI" },
  { cedula: "11861891", name: "RITTER ARTURO REY RINCON", gerencia: "DSI" },
  { cedula: "11867258", name: "RIXIO JOSE ZAMBRANO UGLACIO", gerencia: "DSI" },
  { cedula: "11885168", name: "ALCIDES TORRES", gerencia: "DSI" },
  { cedula: "12216283", name: "MANUEL RAMON DELLAN PINEDA", gerencia: "DSI" },
  { cedula: "12381082", name: "JAIME ALBERTO LOPEZ CONTRERAS", gerencia: "DSI" },
  { cedula: "12440256", name: "WILLIAM ENRIQUE CAÑAS LOPEZ", gerencia: "DSI" },
  { cedula: "12515563", name: "GERARDO RAMON ANTUNEZ BERMUDEZ", gerencia: "DSI" },
  { cedula: "12693795", name: "LUIS ERNESTO MARTINEZ VERGARA", gerencia: "DSI" },
  { cedula: "12697004", name: "LICMIR DEL CARMEN BLANCO AVILA", gerencia: "DSI" },
  { cedula: "12798935", name: "PAUL ALEXANDER CORONADO ARAUJO", gerencia: "DSI" },
  { cedula: "12868518", name: "EDUWI SEGUNDO AMAYA", gerencia: "DSI" },
  { cedula: "12871731", name: "JUAN CARLOS HERNANDEZ RODRIGUEZ", gerencia: "DSI" },
  { cedula: "12872431", name: "LUIS ARNOLDO GOMEZ MORA", gerencia: "DSI" },
  { cedula: "13001454", name: "MATERAN CORDERO, WUILLIAM ANTONIO", gerencia: "DSI" },
  { cedula: "13080910", name: "FERNANDO EZEQUIEL MENDOZA MORA", gerencia: "DSI" },
  { cedula: "13082088", name: "FERNANDO JOSE URDANETA CASTELLANO", gerencia: "DSI" },
  { cedula: "13205884", name: "LUIS MANUEL TERAN UZCATEGUI", gerencia: "DSI" },
  { cedula: "13523786", name: "WUILMER MENDOZA", gerencia: "DSI" },
  { cedula: "13551231", name: "DARWIN DARIO SIBIRA DIAZ", gerencia: "DSI" },
  { cedula: "13628631", name: "ANTONIO JOSE PEÑA MARTINEZ", gerencia: "DSI" },
  { cedula: "13661006", name: "DOUGLAS ENRIQUE VILLALOBOS BARRERA", gerencia: "DSI" },
  { cedula: "13943420", name: "HENRY DAVID GONZALEZ URUETA", gerencia: "DSI" },
  { cedula: "14134276", name: "MAYRA ALEJANDRA VARELA BRAVO", gerencia: "DSI" },
  { cedula: "14150901", name: "MOISES ELIAS MORALES OLIVARES", gerencia: "DSI" },
  { cedula: "14360485", name: "EDUARDO JOSE MORALES MORALES", gerencia: "DSI" },
  { cedula: "14457223", name: "ANGELO DEIVIS FERRER SOTO", gerencia: "DSI" },
  { cedula: "14698598", name: "RAFAEL ALFONSO RINCON VILLALOBOS", gerencia: "DSI" },
  { cedula: "14723834", name: "AUDOMARIO JOSE GARCIA RIVERO", gerencia: "DSI" },
  { cedula: "15053207", name: "HENRY OMAR MESTRE MENDEZ", gerencia: "DSI" },
  { cedula: "15058154", name: "DAYANNA YASMIN RUIZ BLANCO", gerencia: "DSI" },
  { cedula: "15552200", name: "KENNERT ANTONIO GARCIA PORTILLO", gerencia: "DSI" },
  { cedula: "16107972", name: "OMAR JOSE MORAN LOPEZ", gerencia: "DSI" },
  { cedula: "16213667", name: "JUNA CARLOS ORTEGA AGUILAR", gerencia: "DSI" },
  { cedula: "16365866", name: "JOHAN ENRIQUE FINOL CEPEDA", gerencia: "DSI" },
  { cedula: "16652902", name: "CARLOS MANUEL GOMEZ ALTUVE", gerencia: "DSI" },
  { cedula: "16823646", name: "DANILO JOSE CARRIZO NIEVES", gerencia: "DSI" },
  { cedula: "16919739", name: "ALVER ENRIQUE FRANCO", gerencia: "DSI" },
  { cedula: "17188160", name: "ROBERTO LUIS DOMINGUEZ MANZANILLA", gerencia: "DSI" },
  { cedula: "17327669", name: "GUSTAVO ADOLFO SOTO RANGEL", gerencia: "DSI" },
  { cedula: "17336507", name: "JESUS ANGEL PADRON HERNANDEZ", gerencia: "DSI" },
  { cedula: "17635690", name: "ANGEL BENITO HERNANDEZ SANDOVAL", gerencia: "DSI" },
  { cedula: "17858752", name: "JUAN CARLOS ESCALONA ROMAN", gerencia: "DSI" },
  { cedula: "17916099", name: "EZEQUIEL ANTONIO MENDOZA MORA", gerencia: "DSI" },
  { cedula: "17940057", name: "RENNY ENRIQUE MORAN AVILA", gerencia: "DSI" },
  { cedula: "18573488", name: "ALI JOSE GONZALEZ QUIBA", gerencia: "DSI" },
  { cedula: "18732535", name: "EMANUELA ZULEIDA CULTRERA CANELON", gerencia: "DSI" },
  { cedula: "19017005", name: "JOHN STEVE ALBORNOZ PIRELA", gerencia: "DSI" },
  { cedula: "19072220", name: "REGULO ALI RINCON MARTINEZ", gerencia: "DSI" },
  { cedula: "19547689", name: "GREJALROTH LHERIK PINEDA VIDAL", gerencia: "DSI" },
  { cedula: "19938637", name: "RAFAEL ANTONIO LEAL JIMENEZ", gerencia: "DSI" },
  { cedula: "19987557", name: "ALI ALFONSO SANCHEZ COLINA", gerencia: "DSI" },
  { cedula: "20280346", name: "JESUS ALBERTO FUENMAYOR URDANETA", gerencia: "DSI" },
  { cedula: "20428995", name: "JOSE GABRIEL CASTRO NAVA", gerencia: "DSI" },
  { cedula: "21126172", name: "LEONARDO MIJAIL ESCALONA ROMAN", gerencia: "DSI" },
  { cedula: "22056335", name: "ANTHONY DANIEL RAMIREZ BOSCAN", gerencia: "DSI" },
  { cedula: "22069439", name: "JUAN CARLOS POMANERES POMANERES", gerencia: "DSI" },
  { cedula: "22140310", name: "MERVIN JOSE VILLEGAS MONTIEL", gerencia: "DSI" },
  { cedula: "23764150", name: "FRANKLIN JOSE AGUILAR RIOS", gerencia: "DSI" },
  { cedula: "27418263", name: "ANGEL ENRIQUE SOTO GUTIERREZ", gerencia: "DSI" },
  { cedula: "28483989", name: "GABRIEL DE JESUS ACOSTA LEON", gerencia: "DSI" },
  { cedula: "16081976", name: "ARIAS DE JAIMES JOANNA CHIQUIN", gerencia: "DSI" },
  { cedula: "16149666", name: "CAMARILLO RONDON JOEL JOSE", gerencia: "DSI" },
  { cedula: "10449049", name: "ARTEAGA RODRIGUEZ LEANDRO ALBERTO", gerencia: "DSI" },
  { cedula: "10806897", name: "ONEIDA JANETH LEON MONTES DE OCA", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "13024874", name: "PETER LOUIS PIERRE VARGAS", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "13879046", name: "SABRINA DEL CARMEN MARIN GOITIA", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "14496235", name: "EDGAR JOSE COLINA ARIAS", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "14896041", name: "HEBERT DE JESUS MEDINA GONZALEZ", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "15407603", name: "NOLCRY JOSE VALERA ROSALES", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "16727141", name: "JEAN CARLOS GOMEZ FUENMAYOR", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "17230136", name: "RIGOBERTO ANTONIO BRICEÑO ONTIVEROS", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "18285988", name: "ROSALIA VERONICA CARRASQUERO GONZALEZ", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "18832746", name: "JOHANNY ESTER CALDERON MATOS", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "20441468", name: "MARIAN JOSE GOVEA SENSIAL", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "14257017", name: "ANGELICA DEL CARMEN MARVAL DE POLO", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "19568939", name: "MAIRYN GABRIELA MACHADO BENAVIDES", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "5854750", name: "GONZALO IGNACIO DEL CARMEN URDANETA UZCATEGUI", gerencia: "FACILIDADES" },
  { cedula: "6747314", name: "JOSE ENRIQUE AFANADOR SILVA", gerencia: "FACILIDADES" },
  { cedula: "7785176", name: "NORBERTO RAMON VILLALOBOS INCIARTE", gerencia: "FACILIDADES" },
  { cedula: "7869897", name: "NELSON ALFREDO TORRES", gerencia: "FACILIDADES" },
  { cedula: "12696294", name: "ANA MARIA DIAZ CARNEIRO", gerencia: "FACILIDADES" },
  { cedula: "13174528", name: "RIGOBERTO WILDER FLORES SALAS", gerencia: "FACILIDADES" },
  { cedula: "13480262", name: "JORGE LUIS AGUERO MADRIZ", gerencia: "FACILIDADES" },
  { cedula: "14117940", name: "MELISSA CAROLINA MEDINA", gerencia: "FACILIDADES" },
  { cedula: "14863521", name: "JUAN CARLOS FUENTES MARIN", gerencia: "FACILIDADES" },
  { cedula: "15464930", name: "DANNY RAMON DE JESUS RODRIGUEZ GONZALEZ", gerencia: "FACILIDADES" },
  { cedula: "15625150", name: "JOSE LINO SALAZAR ORTEGA", gerencia: "FACILIDADES" },
  { cedula: "15749327", name: "NEHOVER ENRIQUE SOLER PIRELA", gerencia: "FACILIDADES" },
  { cedula: "16621940", name: "WILLIAM ENRIQUE MINORTA JACOME", gerencia: "FACILIDADES" },
  { cedula: "17509265", name: "JUAN CARLOS LUGO GONZALEZ", gerencia: "FACILIDADES" },
  { cedula: "17834137", name: "JOSELIN COROMOTO POLANCO VARELA", gerencia: "FACILIDADES" },
  { cedula: "17938593", name: "CESAR JOSE ROMERO ROMERO", gerencia: "FACILIDADES" },
  { cedula: "20947447", name: "ALEJANDRO ENRIQUE GODOY ATENCIO", gerencia: "FACILIDADES" },
  { cedula: "20948100", name: "OMAR NABIL EL SOUKI EL MAAZ", gerencia: "FACILIDADES" },
  { cedula: "21353310", name: "EDUARDO JOSE SILVA RANGEL", gerencia: "FACILIDADES" },
  { cedula: "25800789", name: "ANGEL ENRIQUE RAMIREZ ANTUNEZ", gerencia: "FACILIDADES" },
  { cedula: "9755697", name: "FRANKLIN DE JESUS ESPINA DIAZ", gerencia: "FACILIDADES" },
  { cedula: "12513832", name: "NESTOR LUIS VILLARREAL PORTILLO", gerencia: "FACILIDADES" },
  { cedula: "14847035", name: "EDIXON JAVIER QUIROZ CHACIN", gerencia: "FACILIDADES" },
  { cedula: "7806048", name: "MERLY JOSEFINA CABRERA ALVARADO", gerencia: "FINANZAS" },
  { cedula: "7818381", name: "EDGAR ANTONIO ZAPATA SANCHEZ", gerencia: "FINANZAS" },
  { cedula: "7979605", name: "DARIO ENRIQUE CRESPO GONZALEZ", gerencia: "FINANZAS" },
  { cedula: "12697136", name: "IRAMA CHIQUINQUIRA URRIBARRI DE OBERTO", gerencia: "FINANZAS" },
  { cedula: "14278883", name: "NORELIS LISETH URRIBARRI PAVOLIS", gerencia: "FINANZAS" },
  { cedula: "14831565", name: "JOHANNY ALEJANDRA MONTAÑA MENDOZA", gerencia: "FINANZAS" },
  { cedula: "14922703", name: "MARYER ESCOLA MACHADO", gerencia: "FINANZAS" },
  { cedula: "15531138", name: "DANIVELIN BETZAIDA GONZALEZ DE ANGARITA", gerencia: "FINANZAS" },
  { cedula: "15624448", name: "RICHARD ENRIQUE LUZARDO PULGAR", gerencia: "FINANZAS" },
  { cedula: "15938298", name: "YARITZA CHIQUINQUIRA VIELMA SAAVEDRA", gerencia: "FINANZAS" },
  { cedula: "17567095", name: "ROY ANTONIO GODOY AZUAJE", gerencia: "FINANZAS" },
  { cedula: "17629756", name: "NAIRALY ANTONIA MILLANO DE ARTIGAS", gerencia: "FINANZAS" },
  { cedula: "17834145", name: "ERENICE MAITHE POLANCO VARELA", gerencia: "FINANZAS" },
  { cedula: "18381034", name: "REBECA ISABEL CABALLERO UZCATEGUI", gerencia: "FINANZAS" },
  { cedula: "18635829", name: "NAKARYS CAROLINA ROMERO HERNANDEZ", gerencia: "FINANZAS" },
  { cedula: "18823718", name: "VANESSA VERONICA ATENCIO DE BERMUDEZ", gerencia: "FINANZAS" },
  { cedula: "19547741", name: "GREILYS MARIA TROCONIZ FLOREZ", gerencia: "FINANZAS" },
  { cedula: "26871171", name: "MARIANGEL ADRIANA GONZALEZ VELASQUEZ", gerencia: "FINANZAS" },
  { cedula: "27056942", name: "INES MARIA MORAN JIMENEZ", gerencia: "FINANZAS" },
  { cedula: "27822702", name: "MARIENIS INCIARTE", gerencia: "FINANZAS" },
  { cedula: "17048776", name: "OLAVES YAKMERY", gerencia: "FINANZAS" },
  { cedula: "12330513", name: "JOHANNA CHIQUINQUIRA VERA RUIZ", gerencia: "FINANZAS" },
  { cedula: "27848103", name: "ANA VILLASMIL", gerencia: "FINANZAS" },
  { cedula: "15986515", name: "MARTINEZ DE CASTELLANOS VIOLETA CH", gerencia: "FINANZAS" },
  { cedula: "13296003", name: "ROLON PENA CARMEN MARINA", gerencia: "FINANZAS" },
  { cedula: "11477424", name: "MARIA ALEJANDRA FERNANDEZ DE NUÑEZ", gerencia: "INGENIERIA DE COSTOS" },
  { cedula: "14337657", name: "ALEXANDRA JOSEFINA RANGEL CARDENAS", gerencia: "INGENIERIA DE COSTOS" },
  { cedula: "14556870", name: "FRANCIA BELEN OLIVAR DE JAIMES", gerencia: "INGENIERIA DE COSTOS" },
  { cedula: "16160482", name: "REAGAN RAMON DIAZ REYES", gerencia: "INGENIERIA DE COSTOS" },
  { cedula: "16689075", name: "ELIZABETH MARIA LUZARDO SERRUDO", gerencia: "INGENIERIA DE COSTOS" },
  { cedula: "27909534", name: "DAVID GUSTAVO BARRETO SEMPRUN", gerencia: "INGENIERIA DE COSTOS" },
  { cedula: "12694991", name: "ROGER EDUARDO RIVERA GONZALEZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "7757506", name: "ARTURO FAIZ CALVO", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "12307014", name: "MILAGROS CHIQUINQUIRA MONTIEL REYES", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "12307878", name: "NINOSKA NOHEMI TROMPIZ OLMOS", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "13301636", name: "JOSE ENRIQUE MEDINA MARIN", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "13529362", name: "DARWIN HERNANDO NAVA REVEROL", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "13745277", name: "JENNIFER COROMOTO PEREZ NAVA", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "14083421", name: "NAILYNETH RAQUELY BORJAS DE BRITO", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "14165966", name: "SANDRA YVETTE PEDROZO ALVARADO", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "14305464", name: "YASENIA DEL CARMEN CHACIN RINCON", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "14475713", name: "ANELISA JOSEFINA HUERTA DELGADO", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "14544693", name: "LIZMAIRA ISIS MARQUEZ SANCHEZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "14657949", name: "JOHANA JOSELIN VILLASMIL RAMIREZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "14833824", name: "JENNY CHIQUINQUIRA MORALES VILLALOBOS", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "15443338", name: "HEYZER YENNYREK VILLALBA GALUE", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "21422280", name: "LUIS JOSE AGUILERA RODRIGUEZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "15763308", name: "CARLOS MANUEL RODRIGUEZ RODRIGUEZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "15937088", name: "NOHELY COROMOTO LOPEZ PEREZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "16548529", name: "JUAN PABLO PEÑA VARGAS", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "16688415", name: "IRIS LORAYNE CARROZ DE GONZALEZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "16987874", name: "MARIO JOSE GARCIA BORREGO", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "17415440", name: "ARACELIS JOSEFINA ABREU AVILA", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "17865073", name: "LEIDY KARINA ALDANA SANTOS", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "18121897", name: "ARENIS CHIQUINQUIRA ROSALES ATENCIO", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "19341586", name: "ANDERSON JAVIER URDANETA SALAS", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "20743382", name: "RICARDO SAMUEL RODRIGUEZ MATOS", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "23554147", name: "FIDEL JOSE MONTILLA LEON", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "26112916", name: "MAYKEL ALEJANDRO LEAL DIAZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "27603737", name: "ORLANDO BARCELO", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "15305967", name: "LUIS JOSE VARGAS PEÑA", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "26550868", name: "PAOLINA TIBISAY DELMORAL BOSCAN", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "15442420", name: "ELAINE BLANCA RODRIGUEZ DE GONZALEZ", gerencia: "INGENIERIA DE PETROLEO" },
  { cedula: "22449053", name: "ALVANYS ANDREINA GONZALEZ VILLALOBOS", gerencia: "INVERSION SOCIAL" },
  { cedula: "7965904", name: "MARIELA BEATRIZ TORRES DE PRIETO", gerencia: "INVERSION SOCIAL" },
  { cedula: "12713663", name: "ODIN JOSE CARRIZO", gerencia: "INVERSION SOCIAL" },
  { cedula: "16365360", name: "JOSE RAFAEL PARRA MORAN", gerencia: "INVERSION SOCIAL" },
  { cedula: "17436480", name: "NOEMI CAICEDO ANGULO", gerencia: "INVERSION SOCIAL" },
  { cedula: "8504912", name: "FRANCISCO JAVIER MORALES HERNANDEZ", gerencia: "LEGAL" },
  { cedula: "14279702", name: "HECTOR JOSE ROSADO", gerencia: "LEGAL" },
  { cedula: "15986979", name: "FABIOLA PATRICIA DEL CARMEN URDANETA NAVA", gerencia: "LEGAL" },
  { cedula: "17820520", name: "ANGIBETH CAROLINA BRACHO CARRILLO", gerencia: "LEGAL" },
  { cedula: "21165251", name: "DANIELA KATIUSKA LABARCA PIÑA", gerencia: "LEGAL" },
  { cedula: "23758830", name: "ANARENNY COROMOTO OLIVARES DABOIN", gerencia: "LEGAL" },
  { cedula: "26263292", name: "DEIRANI DEINES SOTO PIRELA", gerencia: "LEGAL" },
  { cedula: "23768808", name: "JHONATAN JOSUE GUILLEN FERREBUS", gerencia: "LEGAL" },
  { cedula: "4728961", name: "RAFAEL ERNESTO PUERTA FONSECA", gerencia: "MANTENIMIENTO" },
  { cedula: "7625319", name: "ALFONSO ALBERTO ARMIJO TORRES", gerencia: "MANTENIMIENTO" },
  { cedula: "7744748", name: "MANUEL GREGORIO PAEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "7814042", name: "FERNANDO JOSE LANDAETA SANGRONIS", gerencia: "MANTENIMIENTO" },
  { cedula: "7931343", name: "GIOVANNI DE JESUS VILLALOBOS", gerencia: "MANTENIMIENTO" },
  { cedula: "7934441", name: "JESUS ANTONIO OLIVEROS TUBIÑEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "7938788", name: "ALIRIO DE JESUS ZAMBRANO PEÑA", gerencia: "MANTENIMIENTO" },
  { cedula: "7939836", name: "JOSE FRANCISCO SEMPRUN", gerencia: "MANTENIMIENTO" },
  { cedula: "7975370", name: "CARLOS JULIO FREITES FERREBUS", gerencia: "MANTENIMIENTO" },
  { cedula: "8509996", name: "ROBERT JOSE ROSALES TORRES", gerencia: "MANTENIMIENTO" },
  { cedula: "9707754", name: "OMAR FRANCISCO HERNANDEZ FERREBU", gerencia: "MANTENIMIENTO" },
  { cedula: "9708511", name: "LANY BARTOLO VILLALOBOS MORALES", gerencia: "MANTENIMIENTO" },
  { cedula: "9718354", name: "JOSE LUIS MORA CASTRO", gerencia: "MANTENIMIENTO" },
  { cedula: "9722736", name: "DANILO ENRIQUE BRACHO SOTO", gerencia: "MANTENIMIENTO" },
  { cedula: "9732120", name: "FRANCISCO JESUS DSILVA MAURI", gerencia: "MANTENIMIENTO" },
  { cedula: "9740630", name: "FRANCISCO JOSE RODRIGUEZ SALAS", gerencia: "MANTENIMIENTO" },
  { cedula: "9748717", name: "FRANZ REINALDO FLORES FUENMAYOR", gerencia: "MANTENIMIENTO" },
  { cedula: "9752771", name: "JUAN CARLOS AÑEZ SUAREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "9755646", name: "JOSE GREGORIO BRAVO HERNANDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "9776508", name: "ROBERTO DE JESUS BARBOZA MUTIS", gerencia: "MANTENIMIENTO" },
  { cedula: "9811767", name: "EDGAR ANTONIO GOITIA", gerencia: "MANTENIMIENTO" },
  { cedula: "9845503", name: "RENE JESUS VERDE", gerencia: "MANTENIMIENTO" },
  { cedula: "10119049", name: "EDGAR ALI MILLAN MORA", gerencia: "MANTENIMIENTO" },
  { cedula: "10395326", name: "CARMELO LANNI PEREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "10403269", name: "ANGEL JOSE CHACON HERRERA", gerencia: "MANTENIMIENTO" },
  { cedula: "10424657", name: "HUMBERTO HERNANDEZ CHURIO", gerencia: "MANTENIMIENTO" },
  { cedula: "10431910", name: "ROBINSON ALVIAREZ MENDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "10444378", name: "RICHARD ENRIQUE MEDINA ORDOÑEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "10447202", name: "RICARDO JOSE CHOURIO GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "10452069", name: "ANGEL GREGORIO DIAZ RINCON", gerencia: "MANTENIMIENTO" },
  { cedula: "10675463", name: "JAVIER DE JESUS ACOSTA", gerencia: "MANTENIMIENTO" },
  { cedula: "10679261", name: "BALMIRO JOSE LOPEZ PRIETO", gerencia: "MANTENIMIENTO" },
  { cedula: "10917552", name: "ENDER ENRIQUE AVILA CHACIN", gerencia: "MANTENIMIENTO" },
  { cedula: "11045053", name: "JIMY ENRIQUE HERNANDEZ ZABALETA", gerencia: "MANTENIMIENTO" },
  { cedula: "11125085", name: "JOSE FLORENCIO CASTILLO RIVERO", gerencia: "MANTENIMIENTO" },
  { cedula: "11138368", name: "EUSEBIO FERNANDEZ MIQUILENA", gerencia: "MANTENIMIENTO" },
  { cedula: "11253606", name: "JOSE GREGORIO PIRELA RUBIO", gerencia: "MANTENIMIENTO" },
  { cedula: "11256782", name: "GABRIEL ALEXANDER LOPEZ MARTINEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "11281401", name: "JAIRO ENRIQUE MOLERO LISBOA", gerencia: "MANTENIMIENTO" },
  { cedula: "11289799", name: "JAIRO ROBERT SANTIAGO AÑEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "11291165", name: "ELIDO JOSE ZAMBRANO ESTRADA", gerencia: "MANTENIMIENTO" },
  { cedula: "11390916", name: "CARLOS ENRIQUE GONZALEZ MASSIRRUBI", gerencia: "MANTENIMIENTO" },
  { cedula: "11393078", name: "OSCAR SEGUNDO ZAMBRANO VILLALOBOS", gerencia: "MANTENIMIENTO" },
  { cedula: "11394442", name: "ALFREDO JOSE VILORIA CARRASQUERO", gerencia: "MANTENIMIENTO" },
  { cedula: "11528457", name: "REINALDY RAFAEL GARCIA VILLARROEL", gerencia: "MANTENIMIENTO" },
  { cedula: "11608248", name: "LEONARDO JOSE LEON BRACHO", gerencia: "MANTENIMIENTO" },
  { cedula: "11661333", name: "ANGEL ROBINSON BERRUETA GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "11661805", name: "JOAQUIN SEGUNDO GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "11661916", name: "GREGORY ANTONIO MOLERO MORALES", gerencia: "MANTENIMIENTO" },
  { cedula: "11662839", name: "LENIN JOSE SANDOVAL MAGDALENO", gerencia: "MANTENIMIENTO" },
  { cedula: "12381753", name: "MARISELA DEL CARMEN VILLALOBOS", gerencia: "MANTENIMIENTO" },
  { cedula: "12514253", name: "LEONARDO ENRIQUE TORREALBA CANELONES", gerencia: "MANTENIMIENTO" },
  { cedula: "12619773", name: "MORELINE BELL GARCIA SANCHEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "12622365", name: "JOSE ANGEL LEAL ABREU", gerencia: "MANTENIMIENTO" },
  { cedula: "12693516", name: "ESTEBAN LUIS MILLAN BRICEÑO", gerencia: "MANTENIMIENTO" },
  { cedula: "12694366", name: "JOEL JOSE GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "12696560", name: "KELVIS RAMON URDANETA ARTEAGA", gerencia: "MANTENIMIENTO" },
  { cedula: "12697182", name: "JHAN CARLO BERMUDEZ REINOSO", gerencia: "MANTENIMIENTO" },
  { cedula: "12759062", name: "ELIO SEGUNDO RAMON GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "12803671", name: "NADYN DE JESUS JIMENEZ ACOSTA", gerencia: "MANTENIMIENTO" },
  { cedula: "13000597", name: "WILLIAMS JOSE CONTRERAS SOTO", gerencia: "MANTENIMIENTO" },
  { cedula: "13001908", name: "JOSE GREGORIO CASTRO MANAURE", gerencia: "MANTENIMIENTO" },
  { cedula: "13082616", name: "ROBERTO SEGUNDO SALAS NEGRON", gerencia: "MANTENIMIENTO" },
  { cedula: "13297140", name: "OSWALDO JOSE VILLALOBOS TROCONIZ", gerencia: "MANTENIMIENTO" },
  { cedula: "13588473", name: "JOSE MANUEL BUITRAGO", gerencia: "MANTENIMIENTO" },
  { cedula: "13781017", name: "ALEXIS AMADIS RIVERO LAREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "14117008", name: "IRAN JOSE GUILLOTE ROBLES", gerencia: "MANTENIMIENTO" },
  { cedula: "14266605", name: "ENEIDA ALARCON PRECIADO", gerencia: "MANTENIMIENTO" },
  { cedula: "14525728", name: "LUIS DANIEL BUTRON FERNANDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "14698897", name: "LEONARDO RAMON VILLALOBOS RODRIGUEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "14831020", name: "NEHOMAR RAMON BRAVO SANCHEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "14862482", name: "ISAURO RAFAEL ARENAS ANDARA", gerencia: "MANTENIMIENTO" },
  { cedula: "14945831", name: "MARLON JAVIER HERNANDEZ ORTEGA", gerencia: "MANTENIMIENTO" },
  { cedula: "15052665", name: "DANNY RONALD FERNANDEZ FERRER", gerencia: "MANTENIMIENTO" },
  { cedula: "15195084", name: "CARLOS ALEJANDRO ROMERO URDANETA", gerencia: "MANTENIMIENTO" },
  { cedula: "15195909", name: "JOEL RAMON JIMENEZ DIAZ", gerencia: "MANTENIMIENTO" },
  { cedula: "15260061", name: "JOSE JESUS VILLALOBOS JADITH", gerencia: "MANTENIMIENTO" },
  { cedula: "15401842", name: "JOSE FRANCISCO RINCON MENDOZA", gerencia: "MANTENIMIENTO" },
  { cedula: "15562888", name: "FRANKLIN ANTONIO CAMACHO DUARTE", gerencia: "MANTENIMIENTO" },
  { cedula: "15593316", name: "NIOHMAR ANTONIO GOITIA", gerencia: "MANTENIMIENTO" },
  { cedula: "15718889", name: "JUAN RAMON PRIETO", gerencia: "MANTENIMIENTO" },
  { cedula: "15718891", name: "OMAR DE JESUS ZAMBRANO FERNANDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "15720341", name: "JULIAN DAVID PARRA DUQUE", gerencia: "MANTENIMIENTO" },
  { cedula: "15720360", name: "JUNIOR MANUEL PACHECO FINOL", gerencia: "MANTENIMIENTO" },
  { cedula: "15750016", name: "YORBYS JOSE NEGRETTE VILCHEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "15763028", name: "JOSE ALBERTO RINCON COLOMBO", gerencia: "MANTENIMIENTO" },
  { cedula: "15938188", name: "LEANDRO JOSE VILLARREAL SANCHEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "16118534", name: "ROLANDO JESUS ROSALES GARCIA", gerencia: "MANTENIMIENTO" },
  { cedula: "16365108", name: "GUILLERMO ENRIQUE CARROZ URDANETA", gerencia: "MANTENIMIENTO" },
  { cedula: "16365319", name: "EDUARD ELIAS GONZALEZ ARCAYA", gerencia: "MANTENIMIENTO" },
  { cedula: "16688699", name: "BERNARDO ENRIQUE PALMERA QUINTERO", gerencia: "MANTENIMIENTO" },
  { cedula: "17070094", name: "ALVARO LUIS CARBONELL PARRA", gerencia: "MANTENIMIENTO" },
  { cedula: "17096467", name: "DANIEL ENRIQUE TORRES GUTIERREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "17231471", name: "MANUEL JOSE PEREZ PALMAR", gerencia: "MANTENIMIENTO" },
  { cedula: "17327694", name: "GUSTAVO ENRIQUE SOTO RANGEL", gerencia: "MANTENIMIENTO" },
  { cedula: "17414583", name: "MINORLYS DE LOS ANGELES ORTEGA VILLALOBOS", gerencia: "MANTENIMIENTO" },
  { cedula: "17819234", name: "TONNY ENRIQUE CAMPOS HERNANDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "18409160", name: "ISIDRO JOSE CARRILLO GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "18703287", name: "EDGARDO JOSE SAMBRANO MORAN", gerencia: "MANTENIMIENTO" },
  { cedula: "18703600", name: "YASNELIO SEGUNDO GARCIA FERNANDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "18831252", name: "ADELSO LUIS PARRA MONTIEL", gerencia: "MANTENIMIENTO" },
  { cedula: "18988015", name: "ERICK JOSE VELAZQUEZ GARCIA", gerencia: "MANTENIMIENTO" },
  { cedula: "19341251", name: "EUDIS ALEJANDRO QUERO CHOURIO", gerencia: "MANTENIMIENTO" },
  { cedula: "19546027", name: "VICTOR JAVIER BRAVO CAMPO", gerencia: "MANTENIMIENTO" },
  { cedula: "19549780", name: "YRWIN JOSE PEROZO CASTILLO", gerencia: "MANTENIMIENTO" },
  { cedula: "20058701", name: "JOSE GREGORIO URDANETA MONTIEL", gerencia: "MANTENIMIENTO" },
  { cedula: "20059698", name: "ANA KARINA CARRUYO BOSCAN", gerencia: "MANTENIMIENTO" },
  { cedula: "20086994", name: "ANGEL EDUARDO APONTE VENTURA", gerencia: "MANTENIMIENTO" },
  { cedula: "21361048", name: "CARLOS EDUARDO PEREZ MONZANT", gerencia: "MANTENIMIENTO" },
  { cedula: "22232596", name: "ADENIS RAMON URDANETA MUÑOZ", gerencia: "MANTENIMIENTO" },
  { cedula: "23738307", name: "EURELIO ANGEL BENITO PARRA RAMIREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "24484096", name: "JELFRI JOSE SEMPRUN VILLALOBOS", gerencia: "MANTENIMIENTO" },
  { cedula: "24714120", name: "MARIO ADOLFO QUEVEDO MOLERO", gerencia: "MANTENIMIENTO" },
  { cedula: "24922172", name: "JEAN URBINA", gerencia: "MANTENIMIENTO" },
  { cedula: "25975254", name: "ANA KARINA PARRA VALBUENA", gerencia: "MANTENIMIENTO" },
  { cedula: "26356290", name: "LUIS ALBERTO BENITEZ RODRIGUEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "26375538", name: "ANDRY CARVAJAL", gerencia: "MANTENIMIENTO" },
  { cedula: "26418441", name: "ARMANDO JESUS ALBORNOZ FUENMAYOR", gerencia: "MANTENIMIENTO" },
  { cedula: "27056928", name: "JOSE ENRIQUE SOTO AÑEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "27057741", name: "JULIO JOSE FERNANDEZ MUÑOZ", gerencia: "MANTENIMIENTO" },
  { cedula: "27633196", name: "DIEGO ANDRES GARCIA RODRIGUEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "27998711", name: "GUSTAVO ADOLFO MARTINEZ DUARTE", gerencia: "MANTENIMIENTO" },
  { cedula: "24617396", name: "KARLY BETSAIDA CARDOZO ARTIGAS", gerencia: "MANTENIMIENTO" },
  { cedula: "7886902", name: "REVILLA GIOVANNI", gerencia: "MANTENIMIENTO" },
  { cedula: "13829281", name: "JOSE TOMAS RINCON APOLLINI", gerencia: "MANTENIMIENTO" },
  { cedula: "14826970", name: "ANDRY LEGEDT GIL", gerencia: "MANTENIMIENTO" },
  { cedula: "18896750", name: "OLIVER JOSE SANCHEZ PEDRIQUE", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "18703271", name: "LUIS EMIRO MORALES LUZARDO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "5066406", name: "IVAN ENRIQUE VERDE RAMIREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "5507060", name: "CALIXTON THEIDE MARRUFFO GUERRA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "5823922", name: "LUIS EDUARDO LEAL URDANETA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7608462", name: "LARRY JOSE SERRUDO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7690995", name: "NOLBERTO ANTONIO CHAVEZ CORDERO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7817215", name: "HUMBERTO JOSE ORTIZ GUERRERO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7824063", name: "OSWALDO ANTONIO BOHORQUEZ PRIETO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7834261", name: "RAMON ALBERTO LOPEZ HERNANDEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7865162", name: "ALEXI JOSE MEDINA FLORES", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7868531", name: "ERICKSON ANTONIO CHIRINOS CUEVAS", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7887679", name: "CARLOS ENRIQUE MORON VILLANUEVA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7892600", name: "GABRIEL JESUS RANGEL PEREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7894262", name: "SILFREDO DANILO ALDANA HERNANDEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7932908", name: "PABLO GREGORIO TIGRERA SANCHEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7938188", name: "REMIGIO ANTONIO QUINTERO LINARES", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "7975661", name: "OMAR SEGUNDO CARDOZO LEAL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "8501780", name: "RONALDITH ENRIQUE CASTRO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "8503934", name: "DAVID GERARDO OLIVARES BARRIOS", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9113451", name: "EDUAR RAMON PRIETO MALDONADO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9643582", name: "ERNESTO LUIS NIETO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9707209", name: "CARLOS ENRIQUE PEREZ VILLARREAL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9728324", name: "BRUNO BARTOLO DIAZ BARRETO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9769367", name: "JOSE LUIS MEDINA MEDINA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9774620", name: "MELVIN RAFAEL HERNANDEZ PIÑA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9778374", name: "PEDRO JOSE AGUIRRE CHOURIO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9791611", name: "RAFAEL ANGEL GONZALEZ PORTILLO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9796882", name: "LUIS ALBERTO GUERRA RINCON", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10398907", name: "LUIS ALEXANDER ACOSTA ANGARITA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10418350", name: "ENDER JAVIER RIVAS MARQUEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10433005", name: "RAFAEL ISIDRO PALAZZI FERRER", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10433382", name: "EDINSON PADRON MENDOZA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10447959", name: "WILLIAM JOSE RINCON", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10449201", name: "JUAN MANUEL GUERRA MONTILLA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10916298", name: "JOHNNY ANTONIO RINCON CARROZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10918863", name: "JULIO LUIS FERNANDEZ URDANETA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11045013", name: "RICCIO JOSE ACEVEDO GONZALEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11282801", name: "JOHAN RICHARD MUÑOZ GONZALEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11282906", name: "LUIS GREGORIO ROO CARDENAS", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11286836", name: "JOSE GREGORIO LUZARDO AÑEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11317760", name: "NELSON JOSE VILLARREAL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11389299", name: "FERNANDO JOSE LUZARDO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11390013", name: "JOSE GREGORIO FEREIRA CARRUYO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11390185", name: "JUAN GABRIEL RINCON BOSCAN", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11391881", name: "JOSE MANUEL ARAUJO PRIETO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11457939", name: "JOSE ANGEL TALAVERA GONZALEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11473360", name: "FELIX RAMON RODRIGUEZ SEGOVIA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11712927", name: "YURIMAY DEL CARMEN SANCHEZ DE HERNANDEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11865872", name: "GERARDO JOSE SANCHEZ BRAVO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "11889439", name: "JESUS RAMON PEREZ MAVAREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12077825", name: "MOISES ENRIQUE GARRIDO PEREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12098096", name: "GUSTAVO MANUEL MARTINEZ VILCHEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12344407", name: "ELIO RAMON BRAVO VERGEL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12549544", name: "EDWARDS EDWIN CEDEÑO PIÑANGO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12590378", name: "SINRE SALCEDO LEAL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12619081", name: "VALMORE JOSE BOSCAN PINEDA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12620496", name: "JOHNNY SEGUNDO HENRY MORENO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12622022", name: "RICHARD JOSE BOHORQUEZ PRIETO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12712930", name: "GLORIS FABIOLA SANCHEZ ROMERO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12871879", name: "MICHELLE ENRIQUE PERNIA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13004611", name: "ALY NOEL MOLERO MARQUEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13082816", name: "ROBERT DARIO CASTELLANOS GUTIERREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13208265", name: "EGLIS JOSE JORDAN CAZOLA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13297104", name: "DEWIN JOSE GUILLOTE ROBLES", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13402306", name: "EDUARDO JOSE TALAVERA GONZALEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13781345", name: "RICHARD ALBERTO CHAVEZ ARRIETA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13912984", name: "YUNISEX COROMOTO CHOURIO RINCON", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "13932644", name: "FEDERICO JOSE RIOS REYES", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "14181737", name: "RAFAEL HUMBERTO GIL JEREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "14305789", name: "YORMAN JOSE MORAN PRIETO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "14415868", name: "ANDY JOSE LEAL RODRIGUEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "14457327", name: "RICHARD EDUARDO FINOL PUCHI", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "14723976", name: "LISABETH MILAGROS NAVA CEDEÑO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "14896072", name: "GERALDINE BEATRIZ SKINNER AÑEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "15052869", name: "EDIXON JOSE MORAN RINCON", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "15260103", name: "ROBERT SEGUNDO PEREZ GARCIA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "15718259", name: "RUBEN DARIO GODOY CARDOZA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "15719588", name: "HENRRY ANTONIO PARRA BERMUDEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "15748724", name: "PEDRO JOSE GARCIA LOPEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "15987093", name: "MIGUEL ANGEL RINCON YAMARTE", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "16081652", name: "ROSIBEL CRISTINA MENDOZA RANGEL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "16688495", name: "JUAN JOSE RAMON AMAYA URIANA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "16689667", name: "LEIDY JANETH MEDINA HIDALGO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "17181862", name: "IGNACIO JAVIER FINOL GARCIA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "17336437", name: "DOUGLAS ENRIQUE CHIRINOS BARRIOS", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "17635142", name: "LUIS ADOLFO GONZALEZ CHAVEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "17668461", name: "YAZAWA IWAI PORTILLO RAMIREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "17912943", name: "JOHANDRY JOSE MORALES BRACHO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "18319963", name: "DOMINGO GREGORIO ARGEL BADEL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "18395235", name: "ARMANDO RAFAEL ALVAREZ MARIN", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "18572905", name: "VICTOR HUGO MONTIEL JIMENEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "18807112", name: "LUIS JOSE RODRIGUEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "18823732", name: "MILENA MARITZA ROJAS TELLO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "19178574", name: "LUIS EDUARDO MENDOZA RANGEL", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "19210986", name: "DANIEL JOSE GONZALEZ CHAVEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "19285320", name: "NORIS BEATRIZ PEÑA AVENDAÑO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "19694551", name: "MOISES DAVID CABALLERO UZCATEGUI", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "19747328", name: "EDWARD JOSE OSORIO MILLAN", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "19809715", name: "DAVID ENRIQUE HERNANDEZ LUZARDO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "20146194", name: "DAVID JESUS VILLALOBOS TIRADO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "20750117", name: "DULCE MARIA OSORIO MUÑOZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "22475431", name: "ANDRES EDUARDO DIAZ LARSEN", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "23469452", name: "CARLOS JAVIER ALAÑA MONTERO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "23855585", name: "ANABELLA CHIQUINQUIRA D'AMBROSIO MORALES", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "24432342", name: "FELIX EDUARDO AGUERO VALBUENA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "26795170", name: "LUIS FERNANDO MARIN PEREZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "26970629", name: "JORGE FRANCISCO JAIMES OLIVAR", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "27071185", name: "RUTH SAMARA PEÑA CANTILLO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "27395422", name: "LEANDRO JAVIER NUÑEZ URDANETA", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10966927", name: "IRWIN RAFAEL PIRE ROJAS", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "16609581", name: "JUAN GONZALEZ", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "12907751", name: "ANDERSON MATOS", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "9723377", name: "FRANCISCO JOSE LOPEZ SALAS", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "15603678", name: "DANIEL ALEJANDRO ESPINOZA PADRON", gerencia: "PLANIFICACION" },
  { cedula: "13830647", name: "HEILY ADELINA GARCIA DE MARTINEZ", gerencia: "PLANIFICACION" },
  { cedula: "13912989", name: "YUNIBER DEL CARMEN CHOURIO RINCON", gerencia: "PLANIFICACION" },
  { cedula: "13926829", name: "MARIELA DEL VALLE BRAVO DE ARDILA", gerencia: "PLANIFICACION" },
  { cedula: "14562124", name: "HILARION RAUL PARIS AZUAJE", gerencia: "PLANIFICACION" },
  { cedula: "15060902", name: "ROSALYN JOHANNA PIÑA BRAVO", gerencia: "PLANIFICACION" },
  { cedula: "15282675", name: "MARCO ANTONIO CUBA SALAS", gerencia: "PLANIFICACION" },
  { cedula: "21359300", name: "MARIANNY CAROLINA VINCIGUERRA VERA", gerencia: "PLANIFICACION" },
  { cedula: "23554060", name: "KEVIN MANUEL PAZ TORRES", gerencia: "PLANIFICACION" },
  { cedula: "25801452", name: "ANGEL EDECIO DURAN CANO", gerencia: "PLANIFICACION" },
  { cedula: "24021463", name: "JULIO JOSUE BASTIDAS GALLARDO", gerencia: "PLANIFICACION" },
  { cedula: "17393371", name: "GIL MARIA ELENA", gerencia: "PLANIFICACION" },
  { cedula: "7858007", name: "JUAN CARLOS LUGO TROCONIZ", gerencia: "POZOS" },
  { cedula: "11259847", name: "SIRIO SAVIER SIRITT SAAVEDRA", gerencia: "POZOS" },
  { cedula: "11892457", name: "ENORBYS JESUS LIZARDO HANSEN", gerencia: "POZOS" },
  { cedula: "12502179", name: "ALBERTO ALEJANDRO OQUENDO GONZALEZ", gerencia: "POZOS" },
  { cedula: "13918858", name: "FREDDY ALONSO CALDERON HURTADO", gerencia: "POZOS" },
  { cedula: "13930822", name: "NEHOMAR ENRIQUE ZARRAGA PIRELA", gerencia: "POZOS" },
  { cedula: "14151584", name: "GILBERT JOSE GODOY CALDERA", gerencia: "POZOS" },
  { cedula: "14496869", name: "JOSE GREGORIO CARRIZO CHAPARRO", gerencia: "POZOS" },
  { cedula: "14582971", name: "FLORELIA DEL VALLE CHIRINOS DE MACHIN", gerencia: "POZOS" },
  { cedula: "15766554", name: "MILEIDY ANYELIN REYES PAZ", gerencia: "POZOS" },
  { cedula: "16120823", name: "HUGO ENRIQUE DELGADO CASTILLO", gerencia: "POZOS" },
  { cedula: "16621949", name: "WILINGTON MINORTA JACOME", gerencia: "POZOS" },
  { cedula: "17415562", name: "KANE WILLIAMS MORENO RACINES", gerencia: "POZOS" },
  { cedula: "17543391", name: "DANILO ENRIQUE SOTO CASILLA", gerencia: "POZOS" },
  { cedula: "17564061", name: "EVER JOSE SILVA ROMAN", gerencia: "POZOS" },
  { cedula: "18394620", name: "RAMON EDUARDO PEREZ MONZANT", gerencia: "POZOS" },
  { cedula: "20058792", name: "MAYLUZ SARABETH PARRA CUEVAS", gerencia: "POZOS" },
  { cedula: "20580797", name: "HECTOR EMILIO NARIÑO FINOL", gerencia: "POZOS" },
  { cedula: "20725728", name: "DEIVY JOSE TORRES CASANOVA", gerencia: "POZOS" },
  { cedula: "21353473", name: "KENDRITH DAVID CHOURIO SANDOVAL", gerencia: "POZOS" },
  { cedula: "21644031", name: "FANNY JEANINE MAYO AGURTO", gerencia: "POZOS" },
  { cedula: "21684331", name: "JUAN MANUEL SOTO GUTIERREZ", gerencia: "POZOS" },
  { cedula: "23458711", name: "CLAUDIO BENITO FUENMAYOR MUSTONE", gerencia: "POZOS" },
  { cedula: "23463712", name: "ALEXANDRA MARIA CARRIZO PIÑA", gerencia: "POZOS" },
  { cedula: "23569269", name: "MARIANNI VICTORIA PARRA CARREÑO", gerencia: "POZOS" },
  { cedula: "17738459", name: "MORAN PEDRO LUIS", gerencia: "POZOS" },
  { cedula: "18311715", name: "TORRES GABRIEL ALEJANDRO", gerencia: "POZOS" },
  { cedula: "12406893", name: "MEDINA LISANDRO RAFAEL", gerencia: "POZOS" },
  { cedula: "17187391", name: "LEAR ACOSTA DAVID RAMON", gerencia: "POZOS" },
  { cedula: "16080286", name: "GOMEZ WILLIAMS HENRY JAVIER", gerencia: "POZOS" },
  { cedula: "15591894", name: "ARCIA SAMIRA ELENA", gerencia: "POZOS" },
  { cedula: "17327158", name: "GARCIA YANEZ DAVID JOSE", gerencia: "POZOS" },
  { cedula: "19459266", name: "FUENMAYOR BRACHO DAYANA", gerencia: "POZOS" },
  { cedula: "13976145", name: "MATOS DARWIN", gerencia: "POZOS" },
  { cedula: "17136559", name: "VILLAMIZAR DUARTE ELIOMAR JOSE", gerencia: "POZOS" },
  { cedula: "17953961", name: "ALEJANDRO JOSE MANZANO TERAN", gerencia: "POZOS" },
  { cedula: "16728404", name: "DABOIN ORTEGA KENNY RAFAEL", gerencia: "POZOS" },
  { cedula: "11660645", name: "ALEXANDER GONZALEZ", gerencia: "POZOS" },
  { cedula: "11259679", name: "WILMER VILCHEZ CELEDON", gerencia: "POZOS" },
  { cedula: "13242607", name: "BRAVO LEO DANNYS", gerencia: "POZOS" },
  { cedula: "11608380", name: "WILLIAM DE JESUS FUENMAYOR", gerencia: "POZOS" },
  { cedula: "6831693", name: "DENNIS DE JESUS GONZALEZ HERNANDEZ", gerencia: "PROCURA" },
  { cedula: "7885068", name: "ANTONIO MARIA GARCIA MORENO", gerencia: "PROCURA" },
  { cedula: "7938600", name: "ELBANO ENRIQUE FINOL", gerencia: "PROCURA" },
  { cedula: "9114477", name: "AUDIO JOSE SANDOVAL", gerencia: "PROCURA" },
  { cedula: "9741176", name: "ANGEL SEGUNDO LUZARDO", gerencia: "PROCURA" },
  { cedula: "9757106", name: "RAFAEL ALFONSO PULGAR PERICH", gerencia: "PROCURA" },
  { cedula: "10429376", name: "KENELINA BERUSKA CARVAJAL DE ORTEGA", gerencia: "PROCURA" },
  { cedula: "10675940", name: "OSCAR ANTONIO RODRIGUEZ", gerencia: "PROCURA" },
  { cedula: "10917533", name: "JAVIER PEÑA", gerencia: "PROCURA" },
  { cedula: "10917788", name: "ROBERT JOSE MUÑOZ MORAN", gerencia: "PROCURA" },
  { cedula: "11390347", name: "JOHNY DE JESUS JIMENEZ LABARCA", gerencia: "PROCURA" },
  { cedula: "11394607", name: "JOHNNY ENRIQUE RINCON RAVEZ", gerencia: "PROCURA" },
  { cedula: "11660790", name: "GERARDO RAMON RUBIO AÑEZ", gerencia: "PROCURA" },
  { cedula: "11660861", name: "GIOVANNY EMIRO PARRA GONZALEZ", gerencia: "PROCURA" },
  { cedula: "11718073", name: "JIMMY ALBERTO FUENMAYOR QUINTERO", gerencia: "PROCURA" },
  { cedula: "11799696", name: "RAUL ANTONIO SMITH PULIDO", gerencia: "PROCURA" },
  { cedula: "11890852", name: "LUIS DANIEL VIZCAINO VASQUEZ", gerencia: "PROCURA" },
  { cedula: "14657169", name: "CARLOS ALBERTO URDANETA ROMERO", gerencia: "PROCURA" },
  { cedula: "14847016", name: "CARLOS EDUARDO VIDAL RODRIGuez", gerencia: "PROCURA" },
  { cedula: "15747888", name: "LORENA YLIANA NOGUERA SERRUDO", gerencia: "PROCURA" },
  { cedula: "15985122", name: "JUAN JOSE HERNANDEZ", gerencia: "PROCURA" },
  { cedula: "17085455", name: "YENNY ESPERANZA LEAL CACERES", gerencia: "PROCURA" },
  { cedula: "17085627", name: "DAVID RICARDO RAMIREZ PIRELA", gerencia: "PROCURA" },
  { cedula: "17683580", name: "JESSICA ANDREINA CHERRE MORALES", gerencia: "PROCURA" },
  { cedula: "17683752", name: "JUAN JOSE PEÑA FRANCO", gerencia: "PROCURA" },
  { cedula: "18742449", name: "ANDREA DE LOS ANGELES VASQUEZ AIZPURUA", gerencia: "PROCURA" },
  { cedula: "19075089", name: "DANIEL JOSE RINCON VITOLA", gerencia: "PROCURA" },
  { cedula: "20662082", name: "JEAN PAUL VILLEGAS TORRES", gerencia: "PROCURA" },
  { cedula: "23446707", name: "LEONARDO RAFAEL SANCHEZ RINCON", gerencia: "PROCURA" },
  { cedula: "28545758", name: "LUIS RINCON", gerencia: "PROCURA" },
  { cedula: "9777411", name: "JOSE ALBERTO GALUE", gerencia: "PROCURA" },
  { cedula: "10917678", name: "EDUARDO EMIRO ZAMBRANO FUENMAYOR", gerencia: "PROCURA" },
  { cedula: "13080196", name: "MARIO ENRIQUE RINCON", gerencia: "PROCURA" },
  { cedula: "12344104", name: "ALVARO FERNANDEZ RODRIGUEZ", gerencia: "PROCURA" },
  { cedula: "12712281", name: "KYRIA MILAGROS CAROLINA LEON QUEVEDO", gerencia: "PROPIEDADES Y CATASTRO" },
  { cedula: "9763667", name: "KARINA DEL ROSARIO TROMPIZ SOTO", gerencia: "PROPIEDADES Y CATASTRO" },
  { cedula: "11046986", name: "YANELIS DEL CARMEN RINCON PEREIRA", gerencia: "PROPIEDADES Y CATASTRO" },
  { cedula: "11800718", name: "CARLOS ALBERTO MELENDEZ GARCIA", gerencia: "PROPIEDADES Y CATASTRO" },
  { cedula: "12872720", name: "MILEXNA JOSEFINA PRIMERA MARIN", gerencia: "PROPIEDADES Y CATASTRO" },
  { cedula: "19215523", name: "ANTHONY JOSE GONZALEZ AÑEZ", gerencia: "PROPIEDADES Y CATASTRO" },
  { cedula: "7613754", name: "GLENDA RAFAELA URDANETA COLINA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "9767480", name: "MARIA YSABEL RANGEL HERNANDEZ", gerencia: "RECURSOS HUMANOS" },
  { cedula: "11393728", name: "MARIA ELIZABETH JOVITO CHIRINOS", gerencia: "RECURSOS HUMANOS" },
  { cedula: "11450191", name: "KATERINE CAROLINA CORDERO DE PEREIRA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "12713312", name: "MILENYS MILAGROS HERRERA MORLES", gerencia: "RECURSOS HUMANOS" },
  { cedula: "12714510", name: "MARYCRUZ RAMOS DE VILCHEZ", gerencia: "RECURSOS HUMANOS" },
  { cedula: "13082495", name: "KEILA COROMOTO LOPEZ DE GONZALEZ", gerencia: "RECURSOS HUMANOS" },
  { cedula: "14305001", name: "KENNER JOSE GOTOPO URDANETA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "15623708", name: "MENDOZA DE PIRELA, ANA VERONICA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "16366662", name: "ROSA ELENA OCANDO MORAN", gerencia: "RECURSOS HUMANOS" },
  { cedula: "17070336", name: "EDILUZ COROMOTO LABARCA URDANETA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "17636886", name: "EVELIN DEL CARMEN VERA DE MUÑOZ", gerencia: "RECURSOS HUMANOS" },
  { cedula: "18063392", name: "ANGELA MARIA HERNANDEZ LUZARDO", gerencia: "RECURSOS HUMANOS" },
  { cedula: "19214342", name: "CARLOS BENITO TORRES TORRES", gerencia: "RECURSOS HUMANOS" },
  { cedula: "21166905", name: "ROSALBA JOSEFA MEDINA GARCIA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "21691601", name: "EDUAR JAVIER CASTAÑO SAAVEDRA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "26335860", name: "NORKAGLIS ZAMIRA PAEZ FARIA", gerencia: "RECURSOS HUMANOS" },
  { cedula: "28582982", name: "MARIANA DEL CARMEN URDANETA LEAL", gerencia: "RECURSOS HUMANOS" },
  { cedula: "20508321", name: "ANGEL MIGUEL SOTO BOHORQUEZ", gerencia: "RECURSOS HUMANOS" },
  { cedula: "20582904", name: "ALEJANDRA DANIELA ARTEAGA LEON", gerencia: "RECURSOS HUMANOS" },
  { cedula: "14736011", name: "MINELLY SNERY TORREALBA RODRIGUEZ", gerencia: "RELACIONES EXTERNAS" },
  { cedula: "14922541", name: "FLOR ANDREINA RIVAS ROSARIO", gerencia: "RELACIONES EXTERNAS" },
  { cedula: "14206726", name: "IRIS BEATRIZ RUBIO GONZALEZ", gerencia: "RELACIONES EXTERNAS" },
  { cedula: "10425674", name: "YARITZA CHIQUINQUIRA MEDINA QUEVEDO", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "19568688", name: "FERNANDO ALBERTO BULA MAS Y RUBI", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "9780891", name: "MONICA MAILY MOLERO VILLALOBOS", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "7868445", name: "ARTURO JOSE PIÑA GUTIERREZ", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "9795832", name: "MIGUEL ANGEL GUTIERREZ", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "10439947", name: "WILSONNET ANTONIO GONZALEZ MORAN", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "10451447", name: "ANTONIO JOSE APONTE", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "11284072", name: "KARINA ROSA ARGUELLO TORRES", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "12591837", name: "ETNA BEATRIZ NAVA RUIZ", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "13661061", name: "JOANNA DE LOS ANGELES MEDINA RIVERO", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "13757203", name: "JOHANA CECILIA MARCANO OLIVEROS", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "15523660", name: "MILYMAR DEL VALLE GARCIA BORREGO", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "15719865", name: "MELIXZA DEL CARMEN ATENCIO ROMERO", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "16560714", name: "ALBERTO ENRIQUE MENDEZ VERA", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "16687927", name: "CESAR AUGUSTO FERNANDEZ URDANETA", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "18483139", name: "MORISU KATHERINE RIERA SANCHEZ", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "21187864", name: "DIANA JOSE PEREZ GUERRERO", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "24406625", name: "JERLIS COROMOTO PEROZO GONZALEZ", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "25945535", name: "DAVID JOSE GONZALEZ FERRER", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "26710136", name: "DANIELA PAOLA LEON PRIMERA", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "12693528", name: "RINA GABRIELLA VOLPE GOMEZ", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "16622872", name: "LEONARD JAVIER AGUIRRE BAPTISTA", gerencia: "SEGURIDAD E HIGIENE OCUPACIONAL - AMBIENTE" },
  { cedula: "5062504", name: "EDGAR RENE GONZALEZ LOPEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "6886085", name: "EDUIN JESUS FERRER DIAZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7295718", name: "LUIS JOSE CASTILLO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7524098", name: "ARGENIS JOSE IRAUSQUIN RUIZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7692573", name: "FRANCISCO JAVIER PINEDO SANCHEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7793667", name: "RAFAEL ORLANDER MORENO ABRIL", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7807824", name: "HENRRY EDGARDO BARRIOS GONZALEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7838841", name: "ARTURO JOSE ALCANTARA PINEDA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7871706", name: "KENNY ENRIQUE CHIRINO BORJAS", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7889624", name: "LUIS ANGEL CARRIZO OLIVARES", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7939688", name: "YDELFONSO LEON", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "7972992", name: "ONOFRE ENRIQUE RINCON BOSCAN", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "9523845", name: "JUAN JIMENEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "9710042", name: "JILMER JOSE BARRERA RODRIGUEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "9732399", name: "JOSE ALEJANDRO ALMARZA UGARTE", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "9758702", name: "ANIBAL ENRIQUE URDANETA BOSCAN", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "9773655", name: "LENIN ENRIQUE SULBARAN CAMARE", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "10087180", name: "JOSE ANTONIO CHINCHILLA FIGUEROA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "10447400", name: "JOSE GREGORIO GALICIA VILCHEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "10449977", name: "LEONARDO ANTONIO FERRER BRICEÑO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "10919728", name: "LUIS ENRIQUE RINCON PEÑA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "10971408", name: "JOSE LUIS RAMIREZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11245248", name: "NESTOR LUIS GONZALEZ CUBILLAN", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11256277", name: "ESCANDER JAVIER FUENMAYOR LEON", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11290265", name: "SERGIO ELEAZAR MORANTE TORRES", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11299445", name: "JOSE RAMON SOTO FERRER", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11390369", name: "JOSE MARTIN ZAMBRANO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11459249", name: "EDWIN ENRIQUE ANDARA RAMIREZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11609788", name: "ORLANDO JOSE SOLER RIOS", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "11886320", name: "RAFAEL ANGEL DIAZ URDANETA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "12040084", name: "JOSE ORANGEL VILORIA FERNANDEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "12344374", name: "ALEXIS JOSE LEON MORALES", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "12381919", name: "GUILLERMO SEGUNDO DELGADO SUAREZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "12492067", name: "RIGOBERTO RODRIGUEZ VICUÑA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "12697336", name: "JOSE MOISES GODOY", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "13082031", name: "JOSE JAVIER RUBIO FERREBUZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "13370728", name: "DANIEL ABRAHAM RIVERA DAZA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "13471740", name: "DEMETRIO SEGUNDO OBERTO PATIARROYO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "13607848", name: "ENDER JOSE ESIS PRIETO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "13934793", name: "RICHARD JULIO GUANIPA RODRIGUEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "14233857", name: "WILSON JAVIER PALACIOS IBARRA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "14278270", name: "KEILA CAROLINA PARRA GARCIA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "14950427", name: "EUTIMIO RAMON BERMUDEZ BARBOZA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "15287510", name: "ELIO RICHARD TORO ROMERO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "15406498", name: "ODIN RODOLFO LUZARDO BORREGO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "15660689", name: "JOSE LUIS RODRIGUEZ PRIETO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "15691975", name: "ALEJANDRO JOSE TORREALBA PADRON", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "15720663", name: "HENRRY JOSE AVILA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "15939407", name: "JHONY ROBERTO GIL TEJEDA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "15985983", name: "RAFAEL ANDRES QUERALES LANDAETA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "16149208", name: "WILMER ENRIQUE HERNANDEZ MORILLO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "16688462", name: "FABIOLA MUÑOZ DE SEPULVEDA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "16848216", name: "RIGOBERTO JOSE OLIVEROS BRITO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "17334394", name: "RUBEN DARIO CASTELLANOS OQUENDO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "17634040", name: "ENDER JAVIER BOSCAN BOSCAN", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "17635381", name: "PEDRO JESUS OCANDO CHACIN", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "17684201", name: "ISAAC JAVIER VERGARA URDANETA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "18394474", name: "JOAN JOSE PALENCIA GONZALEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "18497433", name: "FABIAN DE JESUS ARAUJO CASTILLO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "18624486", name: "VICTOR ALFONSO HERNANDEZ OSORIO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "18833095", name: "ALEXYS JOSE QUINTERO BUCOUP", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "18987143", name: "NEUDO RAFAEL COLINA CASTELLANO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "19394014", name: "EDWARD FELIPE BALOCO TERAN", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "19971678", name: "MARIO ENRIQUE BARBOZA URDANETA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "20379254", name: "RICARDO ANTONIO PARRA INCIARTE", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "20569422", name: "INDIRA PAOLA GONZALEZ CAZORLA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "20834400", name: "CARLOS EDUARDO LARRAZABAL BALDOMINO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "21230292", name: "JUAN CARLOS LEAL SOTO", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "23471226", name: "JENNIFFER MARIA GUZMAN CONSTANTE", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "23676625", name: "HENRY MANUEL LEON LOPEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "25970130", name: "RAYBER RAFAEL BRAVO URDANETA", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "27491089", name: "WILLIAM DAVID ROJAS FERNANDEZ", gerencia: "SERVICIOS ELECTRICOS" },
  { cedula: "10405323", name: "OLEANDRO JOSE BOHORQUEZ PRIETO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11874898", name: "FELIX ENRIQUE BARROSO HERNANDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "5779982", name: "JOSE EMIGDIO ORTEGANO URBINA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "5977559", name: "MARIA AUXILIADORA QUINTERO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "6033776", name: "JOSE JESUS MEZA GUILLEN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7529858", name: "JUANA RAMONA GOMEZ PETIT", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7693870", name: "ISNERIO SEGUNDO GARCIA LABARCA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7741072", name: "JAVIER RAMON CHIRINOS ESCALONA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7810333", name: "YSISLIO ANGEL ATENCIO BRAVO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7894569", name: "ANGEL ENRIQUE GONZALEZ PUCHE", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7903706", name: "JOEL ENRIQUE PEREZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "7932436", name: "LISANDRO ANTONIO MONTANA GARCIA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "7937654", name: "JOSE LUIS RODRIGUEZ RODRIGUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7939456", name: "NESTOR LUIS ATENCIO BRAVO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "7952523", name: "JUAN CARLOS BARBOZA SULBARAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "8501148", name: "RAMON JOSE CARRUYO GONZALEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "8508388", name: "MARTIN EMILIO MARTINEZ OBANDO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9113989", name: "EVELIA ZULEIMA JARDEL RODRIGUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9710962", name: "ALBERTO CARLO BATTIGELLI LUNA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "9721781", name: "GUSTAVO ADOLFO VILLALOBOS FERNANDEZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "9735304", name: "VINICIO ENRIQUE GONZALEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9741174", name: "DUVIS DE JESUS LUZARDO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "9757050", name: "ARSENIo BENITO URDANETA BOSCAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9757278", name: "LEONEL ENRIQUE BRACHO PINO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9759179", name: "NOLBERTO JOSE PATIÑO NIEVES", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9764937", name: "WILMER JOSE ATENCIO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9765625", name: "EDDY ENRIQUE MORAN PEREZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "9781086", name: "NELSON ENRIQUE FERNANDEZ FONSECA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9786654", name: "JAIME RAMON GONZALEZ LAGUNA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "9796466", name: "PEDRO JOSE ALVAREZ URDANETA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "9797123", name: "ALEJANDRO JOSE SOTO FUENMAYOR", gerencia: "SERVICIOS GENERALES" },
  { cedula: "9828484", name: "GREGORIO RAFAEL DE L HURTADO DURAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "10418795", name: "EDUARDO EMIRO LUENGO PELEY", gerencia: "SERVICIOS GENERALES" },
  { cedula: "10444745", name: "EIVIS JOSE BASABE PEREZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "10449300", name: "FRANKLIN TEOBALDO AGUILAR PEÑALOZA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "10676395", name: "EUGLYS JOSE BARILLAS VILLALOBOS", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "10677363", name: "VINICIO SEGUNDO GONZALEZ MARTINEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "10861605", name: "LUIS ALFREDO GRATEROL PALACIOS", gerencia: "SERVICIOS GENERALES" },
  { cedula: "10918861", name: "ANGEL ANTONIO CUBILLAN ZAMBRANO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11045014", name: "ROGELIO ANTONIO URDANETA ZAMBRANO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11045051", name: "GRAYFA JOSEFINA PINEDA MONTIEL", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "11045130", name: "JORGE LUIS GONZALEZ REYES", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "11255208", name: "ANGEL ALBERTO AVILA ZAMBRANO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11257841", name: "OSCAR RAFAEL AVILA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "11287461", name: "EDGARDO JOSE GAMEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11288287", name: "RICHARD RENNE MENDEZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "11288290", name: "EGGLY JOSE FERNANDEZ URDANETA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11389834", name: "BRUNEQUILDO SEGUNDO URDANETA FUENMAYOR", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11390055", name: "ALEXANDER ENRIQUE VILLASMIL BOHORQUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11390462", name: "DENNYS JOSE DIAZ BOHORQUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11390834", name: "ADENIS RAMON URDANETA MEDERO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11392723", name: "ELI JOSE BRAVO BRAVO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11662375", name: "RAFAEL ANTONIO RONDON PINEDA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "11913305", name: "NELLY JULIO MERCADO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12098811", name: "RUBIA HALINA PARDO URDANETA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "12099814", name: "YENNY COROMOTO VILORIA FERREBUZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12099934", name: "YONANI ENRIQUE AVILA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12211987", name: "BELKYS DEL VALLE HERRERA CHACIN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12212127", name: "JOSE LUIS PARRAGA PIRELA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12344073", name: "ENDER JOSE ZAMBRANO BEDOYA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12356713", name: "JOSE GREGORIO SIERRA BERMUDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12379536", name: "ROBERT JOSE OCHOA AMESTY", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12514825", name: "ERVIS OMAR MENDOZA DELGADO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12619990", name: "IVAN RENE NAVA PARRA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12804752", name: "FREDDY ANTONIO ZAMBRANO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "12839095", name: "GREGORIO COROMOTO VAZQUEZ MEJIAS", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12868207", name: "JOSE JAVIER ZAMBRANO COLINA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12873106", name: "DOLLYS MARYS ESPINA DE SALAZAR", gerencia: "SERVICIOS GENERALES" },
  { cedula: "12873254", name: "OMAR ENRIQUE PARRA BRACHO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "13082636", name: "ALEXANDER JOSE GONZALEZ BARROSO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "13243402", name: "ALEXIS ANTONIO AVILA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13297584", name: "FREILY JOSE URDANETA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13298099", name: "MAIGUALIDA DEL CARMEN COLINA TORO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13420113", name: "DOUGLAS ALBERTO SIERRA BERMUDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13685854", name: "CARLOS AUGUSTO GOMEZ HERNANDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13819546", name: "FREDDY ENRIQUE RODRIGUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13901264", name: "JIMMY ALBERTO VENTURA QUERO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13912237", name: "FRANCISCO JIMENEZ CARDENAS", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14235808", name: "GUILLERMO ENRIQUE ARGUELLES GOMEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14305329", name: "MARLON RAMON BOSCAN SUAREZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14511261", name: "NOLBERTO JESUS SALAZAR VEGA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "14553260", name: "MAHOMETT WILLIAN MONTIEL BUSTAMANTE", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14556234", name: "YEAN CARLOS COLMENARES BASTIDAS", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14698863", name: "VICTOR MANUEL ARENAS SANTANA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14862330", name: "EDDY DEL CARMEN ALMARZA ZAMBRANO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14863946", name: "JUAN MANUEL MELEAN CAMARGO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "14895972", name: "ANDRIS JOSE LABARCA LABARCA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "14945719", name: "HUGO ENRIQUE GONZALEZ AVILA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "15011328", name: "JANER CASTELLAR ARRIETA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "15058381", name: "JOCSELYN GORETTY MATHEUS ARANAGA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "15193093", name: "OSCAR MANUEL URDANETA ROMERO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "15195440", name: "BENITO DE JESUS LABARCA VILLALOBOS", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "15239315", name: "JAIDER RAFAEL BRITO ROMERO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "15260852", name: "JOAN LEONER SEGUNDO MORAN DAVILA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "15718255", name: "KRISTEL IRENE RODRIGUEZ QUINTERO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "15718962", name: "NOLBERTO JOSE MORAN CUBILLAN", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "15719509", name: "MARCIAL DE JESUS BARRIENTOS CUBILLAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "15747181", name: "ELAINE CAROLINA ROMERO FERNANDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16187574", name: "GABRIEL ENRIQUE LOPEZ VAZQUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16366073", name: "JOHEL JOSE BOSCAN BARRIOS", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "16367933", name: "KELLY RONALD VERA RUBIO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16609919", name: "JOHANDRY JOSE VELAZCO PAZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16687608", name: "ADENIS JOSE URDANETA BOSCAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16689076", name: "ELISAUL SEGUNDO LUZARDO SERRUDO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "16689456", name: "JESUS GUILLERMO FERRER FERRER", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16731914", name: "ANGELES JOHANA MONTILLA PARRA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16919016", name: "NORALITH DEL CARMEN NIÑO ZAMBRANO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16919365", name: "BRISNELY DEL CARMEN ZAMBRANO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16986555", name: "INGRID COROMOTO ESPINOZA MORENO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16986673", name: "ALEXANDER RAFAEL NIETO QUIBA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "16989165", name: "ANGEL SEGUNDO PIRELA FERRER", gerencia: "SERVICIOS GENERALES" },
  { cedula: "17044437", name: "NELSON JUNIOR ARAUJO TERAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "17070293", name: "ENRY BENITO PORTILLO LOPEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "17086626", name: "ROSA MARINA LOZANO SALAZAR", gerencia: "SERVICIOS GENERALES" },
  { cedula: "17181381", name: "DAYANA MARIA COLINA PEREZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "17415290", name: "YOURIS JOSE RODRIGUEZ BOSCAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "17604064", name: "JHORMAN ANTONIO MEJIA BANITUTE", gerencia: "SERVICIOS GENERALES" },
  { cedula: "17634036", name: "LUZ MARINA JOSEFINA FERNANDEZ FERNANDEZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "17634083", name: "JESUS ANGEL ZAMBRANO FERNANDEZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "17634085", name: "JULIO CESAR ZAMBRANO FERNANDEZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "17634995", name: "ARQUIMEDES JAVIER PALMAR ATENCIO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "17938093", name: "KELVIN KENDRY MONTERO RINCON", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18008285", name: "JUAN JOSE ROSALES RODRIGUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18056371", name: "DERWIS FEIDERMAN VERGARA MARQUEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18371094", name: "JULIO CESAR GARCIA DURAN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18372614", name: "MARINELLY CAROLINA HERNANDEZ BERMUDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18383158", name: "ALAN DEIVIS PRIETO VILLASMIL", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18383664", name: "JEAN POL ANGELASTRI URDANETA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18503383", name: "CESAR ALEXANDRO RANGEL GOMEZ", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "18575307", name: "ALVARO ANTONIO ANGARITA PIMIENTO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "18624705", name: "GERALDO JOSE BADELL FERRER", gerencia: "SERVICIOS GENERALES" },
  { cedula: "19342247", name: "EDUIN CAICEDO", gerencia: "SERVICIOS GENERALES" },
  { cedula: "19408187", name: "PATRICIA CAROLINA CHAVEZ DE HERNANDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "21228464", name: "MIGUEL JESUS PARRA CORONA", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "23888768", name: "RAFAEL RUBEN RAMIREZ MATOS", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "26032293", name: "KARLINA PAOLA GARCIA MEDERO", gerencia: "SERVICIOS LOGISTICOS" },
  { cedula: "26416619", name: "KEILY DE LOS ANGELES BRACHO LOPEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "27847479", name: "ALFREDO ALEJANDRO BARRIOS RANGEL", gerencia: "SERVICIOS GENERALES" },
  { cedula: "28252231", name: "JAVIER CIPOLLA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "29541017", name: "MAGDANIELA MENDOZA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "30250984", name: "MARIA GABRIELA DE LOS ANGELES VILCHEZ TROCONIZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "83123479", name: "JOSE LUIS NOBLE ARRIETA", gerencia: "SERVICIOS GENERALES" },
  { cedula: "7439344", name: "ROCIO DE LOS ANGELES ESCALONA DUN", gerencia: "SERVICIOS GENERALES" },
  { cedula: "19409921", name: "CELENE DEL CARMEN URDANETA FERNANDEZ", gerencia: "SERVICIOS GENERALES" },
  { cedula: "13575495", name: "CARINA JUDITH SANDOVAL DE VERA", gerencia: "CONTRATACION" },
  { cedula: "16559305", name: "DAMARIS CAROLINA FUENMAYOR AÑEZ", gerencia: "CONTRATACION" },
  { cedula: "9784089", name: "BARBARA ISABEL RODRIGUEZ ORDOÑEZ", gerencia: "INVERSION SOCIAL" },
  { cedula: "7674051", name: "EFREN SEGUNDO NAVA FERRER", gerencia: "DSI" },
  { cedula: "7860226", name: "OSCAR ANTONIO RODRIGUEZ SUAREZ", gerencia: "DSI" },
  { cedula: "10440740", name: "BRAWLEY JOSE SALAS COLINA", gerencia: "DSI" },
  { cedula: "12212341", name: "MONICA ELENA BERRUETA DIAZ", gerencia: "DSI" },
  { cedula: "12514489", name: "HENRY ANTONIO ALVARADO VENTURA", gerencia: "DSI" },
  { cedula: "13561237", name: "ELVIS DANIEL GONZALEZ VILLAMIZAR", gerencia: "DSI" },
  { cedula: "15013732", name: "LUIS GUILLERMO GUILLEN FUENMAYOR", gerencia: "DSI" },
  { cedula: "16367943", name: "ANDRY JESUS BARRIOS BUI", gerencia: "DSI" },
  { cedula: "8336673", name: "NELSON RIVAS NIEVES", gerencia: "DSI" },
  { cedula: "6338873", name: "ROMMEL ANTONIO WHILCHY MORALES", gerencia: "ESTUDIOS INTEGRADOS" },
  { cedula: "12098276", name: "HENRY JOSE VILLASMIL BOSCAN", gerencia: "GERENCIA GENERAL" },
  { cedula: "5853563", name: "WILLIAM JOSE GALBAN BRACHO", gerencia: "MANTENIMIENTO" },
  { cedula: "7840311", name: "REINALDO ANTONIO ROMERO ALVAREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "7976872", name: "LUIGGI GREGORIO MORAN GUTIERREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "9722931", name: "EDUARDO ERNESTO SANTRICH URQUIJO", gerencia: "MANTENIMIENTO" },
  { cedula: "9723152", name: "OMAR RAFAEL AGUILAR URDANETA", gerencia: "MANTENIMIENTO" },
  { cedula: "9749617", name: "JOSE LUIS MORALES MARTINEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "10211071", name: "NESTOR JOSE BAEZ GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "10451995", name: "ROBIN JOSE CHAVEZ MARQUEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "10598748", name: "FABIO SEGUNDO MOSQUERA LOPEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "11389955", name: "LOHANY ENRIQUE ROSALES DURAN", gerencia: "MANTENIMIENTO" },
  { cedula: "12099640", name: "RICHARD JAVIER AÑEZ HURTADO", gerencia: "MANTENIMIENTO" },
  { cedula: "13080422", name: "CARLOS JAVIER ZAMBRANO", gerencia: "MANTENIMIENTO" },
  { cedula: "13244052", name: "LEONIDIS JOSE URDANETA ORDOÑEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "13528560", name: "GERARDO ANTONIO SUAREZ URDANETA", gerencia: "MANTENIMIENTO" },
  { cedula: "13590763", name: "JAVIER ALBERTO SILVA SOTO", gerencia: "MANTENIMIENTO" },
  { cedula: "14116336", name: "NEYELIN ROSARIO CARROZ HERNANDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "14496676", name: "JOE MAYKER HERNANDEZ SANCHEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "16304342", name: "ELIO JOSE MORANTE GONZALEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "17151832", name: "LUIS EDUARDO FERNANDEZ BRAVO", gerencia: "MANTENIMIENTO" },
  { cedula: "17668657", name: "ALONSO JOSE OJEDA RIVERO", gerencia: "MANTENIMIENTO" },
  { cedula: "18063294", name: "LUIS ALFONSO SUAREZ ESPINOZA", gerencia: "MANTENIMIENTO" },
  { cedula: "18284642", name: "JHONNY RAFAEL NAVEDA GARCIA", gerencia: "MANTENIMIENTO" },
  { cedula: "18311407", name: "DIXSON JOSE OLIVARES MACHIN", gerencia: "MANTENIMIENTO" },
  { cedula: "20725865", name: "JOSE AVELINO PRIETO BERMUDEZ", gerencia: "MANTENIMIENTO" },
  { cedula: "20985921", name: "GUSTAVO JOSE GALBAN RIOS", gerencia: "MANTENIMIENTO" },
  { cedula: "29526004", name: "ROBERTO EMILIO MOGOLLON GUTIERREZ", gerencia: "MANTENIMIENTO" },
  { cedula: "9748877", name: "OSCAR ALBERTO VALBUENA PERDOMO", gerencia: "OPERACIONES DE PRODUCCION" },
  { cedula: "10409671", name: "PEDRO EMILIANO MOGOLLON MAVAREZ", gerencia: "OPERACIONES DE PRODUCCION" },

];

export const generateDefaultPassengers = async (): Promise<Passenger[]> => {
  const { generateQRCode, QRData } = await import('./qr');
  const passengers: Passenger[] = [];
  
  for (let i = 0; i < defaultPassengersData.length; i++) {
    const passengerData = defaultPassengersData[i];
    
    try {
      const qrData: QRData = {
        cedula: passengerData.cedula,
        name: passengerData.name,
        gerencia: passengerData.gerencia,
        timestamp: new Date().toISOString()
      };
      
      const qrCode = await generateQRCode(qrData);
      
      const passenger: Passenger = {
        id: (Date.now() + i).toString(),
        name: passengerData.name,
        cedula: passengerData.cedula,
        gerencia: passengerData.gerencia,
        qrCode,
        createdAt: new Date().toISOString()
      };
      
      passengers.push(passenger);
    } catch (error) {
      console.error(`Error generando QR para ${passengerData.name}:`, error);
    }
  }
  
  return passengers;
};